from easydict import EasyDict as edict

__C = edict()

model_cfg = __C

# COMMON+ model options.
__C.COMMONPLUS = edict()
__C.COMMONPLUS.FEATURE_CHANNEL = 512
__C.COMMONPLUS.ALPHA = 0.4
__C.COMMONPLUS.DISTILL = True
__C.COMMONPLUS.WARMUP_STEP = 0
__C.COMMONPLUS.MOMENTUM = 0.995
__C.COMMONPLUS.SOFTMAXTEMP = 0.07
__C.COMMONPLUS.QUEUE_SIZE = 0
__C.COMMONPLUS.SK_ITER_NUM = 20
__C.COMMONPLUS.SK_EPSILON = 1.0e-10
__C.COMMONPLUS.SK_TAU = 0.05
__C.COMMONPLUS.TRANSFORMER_GNN = True
# __C.COMMONPLUS.STEP2 = 2000

__C.NGM = edict()
__C.NGM.GNN_LAYER = 1
__C.NGM.GNN_FEAT = [16]
__C.NGM.SK_EMB = 1
__C.NGM.SK_TAU = 0.005
__C.NGM.EDGE_EMB = False



__C.ATTN = edict()
__C.ATTN.SWITCH = False
__C.ATTN.DEPTH = 1
__C.ATTN.IN_DIM = [1]
__C.ATTN.HEAD = [2]
__C.ATTN.OUT_DIM = [16]
__C.ATTN.SK_EMB = 0
__C.ATTN.RECURRENCE = 1